name: Build APK and Notify Slack

on:
  push:
    branches:
      - '*' # Adjust to your main branch name

jobs:
  build:
    name: Build APK on macOS
    runs-on: macos-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22' # Use the version compatible with your project

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Send Slack Notification on success
      - name: Notify Slack - Success
        if: success()  # This condition will trigger when the job is successful
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"✅ CI/CD Pipeline succeeded for React Native project."}' $SLACK_WEBHOOK_URL

      # Send Slack Notification on failure
      - name: Notify Slack - Failure
        if: failure()  # This condition will trigger when the job fails
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"❌ CI/CD Pipeline failed for React Native project."}' $SLACK_WEBHOOK_URL
